RATIS-672. Vagrant test's Maven 404's
Trying to get Clay's patch working -- call out to binary_locations.sh
before launching Yetus to build the docker image.

Re-application after revert. Needed to make sure binary_locations.sh
is invoked before building Docker so that PreCommit doesn't fail.

Signed-off-by: Josh Elser <elserj@apache.org>
Co-authored-by: Josh Elser <elserj@apache.org>

diff --git a/dev-support/vagrant/Vagrantfile b/dev-support/vagrant/Vagrantfile
--- a/dev-support/vagrant/Vagrantfile
+++ b/dev-support/vagrant/Vagrantfile
@@ -78,6 +78,9 @@ Vagrant.configure('2') do |config|
     # install packages
     ratisbuild.vm.provision :shell, name: 'Install Packages', inline: <<-EOH
       set -e
+      # load central file URLs and checksums
+      source #{RATIS_PATH}/dev-support/binary_locations.sh
+
       # setup /usr/local/bin for non-packaged software
       if [[ $(egrep -c 'PATH.*/usr/local/bin' /etc/environment) -eq 0 ]]; then
         echo 'export PATH=${PATH}:/usr/local/bin' >> /etc/environment
@@ -89,14 +92,24 @@ Vagrant.configure('2') do |config|
 
       # install Maven
       mkdir -p /usr/local
-      wget --continue http://apache.mirrors.ionfish.org/maven/maven-3/3.6.0/binaries/apache-maven-3.6.0-bin.tar.gz
-      tar -xzf apache-maven-3.6.0-bin.tar.gz -C /usr/local
-      [ -L /usr/local/bin/mvn ] || ln -s /usr/local/apache-maven-3.6.0/bin/mvn /usr/local/bin/mvn
+      wget --continue "$ratis_maven_url"
+      if [[ "$(sha512sum "$ratis_maven_file")" != \
+            "$ratis_maven_sum  $ratis_maven_file" ]]; then
+        echo "Checksum failed for $ratis_maven_file" > /dev/stderr
+        exit 1
+      fi
+      tar -xzf "$ratis_maven_file" -C /usr/local
+      [ -L /usr/local/bin/mvn ] || ln -s /usr/local/apache-maven-*/bin/mvn /usr/local/bin/mvn
 
       # Namazu dependencies
       apt-get install -y git libnetfilter-queue-dev libzmq3-dev
-      wget --continue https://dl.google.com/go/go1.11.2.linux-amd64.tar.gz
-      tar -xzf go1.11.2.linux-amd64.tar.gz -C /usr/local
+      wget --continue "$ratis_go_url"
+      if [[ "$(sha256sum "$ratis_go_file")" != \
+            "$ratis_go_sum  $ratis_go_file" ]]; then
+        echo "Checksum failed for $ratis_go_file" > /dev/stderr
+        exit 1
+      fi
+      tar -xzf "$ratis_go_file" -C /usr/local
       [ -L /usr/local/bin/go ] || ln -s /usr/local/go/bin/go /usr/local/bin/go
     EOH
 
@@ -109,6 +122,8 @@ Vagrant.configure('2') do |config|
       export GOROOT=/usr/local/go
       export GOPATH=`pwd`
       # for some reason seelog fails to pull automatically
+      # Go should check its checksum database on go get per
+      # https://blog.golang.org/module-mirror-launch
       go get -u github.com/cihub/seelog
       ./build
     EOH
@@ -122,7 +137,7 @@ Vagrant.configure('2') do |config|
       # or otherwise into /etc/environment
       . /etc/environment
       cd #{RATIS_PATH}
-      mvn package -DskipTests
+      mvn clean install assembly:single -DskipTests=true
     EOH
 
     ratisbuild.vm.provider :virtualbox do |vb|
@@ -133,6 +148,10 @@ Vagrant.configure('2') do |config|
     end
 
     ratisbuild.vm.box = 'ubuntu/bionic64'
+    ratisbuild.vm.box_version = '20190918.0.0'
+#   TODO: This seems to break vagrant destroy -f ratis-build
+#    ratisbuild.vm.box_checksum_type = 'sha256'
+#    ratisbuild.vm.box_checksum = 'ed0ac96a5ee41c8a2abff854c6ed1cefbc1cf60a53f1dfd283d66c27bf1c0d4a'
   end
 
   # Configure a generic VM with three Ratis servers
